[[redirects]]
  from = "http://krevv.com/*"
  to = "https://www.krevv.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://krevv.com/*"
  to = "https://www.krevv.com/:splat"
  status = 301
  force = true
